eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8699/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-consumer
    api-b:
      path: /api-b/**
      serviceId: study-ms

